import type { ArchitectureSizingResult } from "@/lib/sizing/architectureSizing";
import type {
  BESSBlock,
  BlockTransformer,
  ConversionStation,
  MVBus,
  MVFeeder,
  PCSModule,
} from "@/types/electrical";
import type { EvidenceRef, EvidencedValue } from "@/types/evidence";

export type BlockArchitectureGeneratorInput = {
  sizing: Pick<
    ArchitectureSizingResult,
    "containers" | "stations" | "feeders" | "resolved" | "installedPowerMVA"
  >;
  manufacturer?: string;
  stationModel?: string;
  pcsModuleModel?: string;
  stationPrefix?: string;
  blockPrefix?: string;
  containerPrefix?: string;
  feederPrefix?: string;
  busPrefix?: string;
  stationStartIndex?: number;
  feederStartIndex?: number;
  busStartIndex?: number;
  collectorVoltageKv?: number;
  lvVoltageKv?: number;
  pcsModulesPerStation?: number;
  pcsModulePowerMVA?: number;
  nominalAcVoltageV?: number;
  dcVoltageRangeV?: [number, number];
  transformerVectorGroup?: string;
  transformerCooling?: string;
  feedersPerBus?: number;
  evidence?: EvidenceRef[];
};

export type BlockArchitectureGeneratorResult = {
  blocks: BESSBlock[];
  conversionStations: ConversionStation[];
  mvFeeders: MVFeeder[];
  mvBuses: MVBus[];
  diagnostics: {
    containers: number;
    stations: number;
    feeders: number;
    mvBuses: number;
    containersPerStation: number;
    stationsPerFeeder: number;
    feedersPerBus: number;
    emptyContainerSlots: number;
    installedPowerMVA: number;
  };
};

type ResolvedOptions = Required<
  Pick<
    BlockArchitectureGeneratorInput,
    | "manufacturer"
    | "stationModel"
    | "pcsModuleModel"
    | "stationPrefix"
    | "blockPrefix"
    | "containerPrefix"
    | "feederPrefix"
    | "busPrefix"
    | "stationStartIndex"
    | "feederStartIndex"
    | "busStartIndex"
    | "collectorVoltageKv"
    | "lvVoltageKv"
    | "pcsModulesPerStation"
    | "pcsModulePowerMVA"
    | "nominalAcVoltageV"
    | "dcVoltageRangeV"
    | "transformerVectorGroup"
    | "transformerCooling"
    | "feedersPerBus"
  >
> & {
  evidence: EvidenceRef[];
};

function pad(value: number): string {
  return String(value).padStart(2, "0");
}

function derivedEvidence(note: string): EvidenceRef {
  return {
    documentId: "__none__",
    confidence: "derived",
    note,
  };
}

function evidencedNumber(
  value: number,
  unit: string,
  evidence: EvidenceRef[]
): EvidencedValue<number> {
  return {
    value,
    unit,
    evidence:
      evidence.length > 0
        ? evidence
        : [derivedEvidence("Generated by preliminary block architecture generator")],
  };
}

function resolveOptions(
  input: BlockArchitectureGeneratorInput
): ResolvedOptions {
  const stationPowerMVA = input.sizing.resolved.stationPowerMVA;
  const pcsModulesPerStation = input.pcsModulesPerStation ?? 2;
  return {
    manufacturer: input.manufacturer ?? "Sungrow",
    stationModel: input.stationModel ?? "SC5000UD-MV",
    pcsModuleModel: input.pcsModuleModel ?? "SC5000UD-MV PCS module",
    stationPrefix: input.stationPrefix ?? "PB",
    blockPrefix: input.blockPrefix ?? "block-pb",
    containerPrefix: input.containerPrefix ?? "container-pb",
    feederPrefix: input.feederPrefix ?? "feeder",
    busPrefix: input.busPrefix ?? "BP",
    stationStartIndex: input.stationStartIndex ?? 1,
    feederStartIndex: input.feederStartIndex ?? 1,
    busStartIndex: input.busStartIndex ?? 1,
    collectorVoltageKv: input.collectorVoltageKv ?? 33,
    lvVoltageKv: input.lvVoltageKv ?? 0.9,
    pcsModulesPerStation,
    pcsModulePowerMVA:
      input.pcsModulePowerMVA ?? stationPowerMVA / pcsModulesPerStation,
    nominalAcVoltageV: input.nominalAcVoltageV ?? 900,
    dcVoltageRangeV: input.dcVoltageRangeV ?? [1300, 1500],
    transformerVectorGroup: input.transformerVectorGroup ?? "Dy11",
    transformerCooling: input.transformerCooling ?? "ONAN",
    feedersPerBus: input.feedersPerBus ?? 5,
    evidence: input.evidence ?? [],
  };
}

function stationNumber(index: number, options: ResolvedOptions): number {
  return options.stationStartIndex + index;
}

function feederNumber(index: number, options: ResolvedOptions): number {
  return options.feederStartIndex + index;
}

function busNumber(index: number, options: ResolvedOptions): number {
  return options.busStartIndex + index;
}

function stationId(index: number, options: ResolvedOptions): string {
  return `station-${options.stationPrefix.toLowerCase()}${pad(
    stationNumber(index, options)
  )}`;
}

function blockId(index: number, options: ResolvedOptions): string {
  return `${options.blockPrefix}${pad(stationNumber(index, options))}`;
}

function containerId(
  stationIndex: number,
  slot: number,
  options: ResolvedOptions
): string {
  return `${options.containerPrefix}${pad(
    stationNumber(stationIndex, options)
  )}-c${slot}`;
}

function feederId(index: number, options: ResolvedOptions): string {
  return `${options.feederPrefix}-${pad(feederNumber(index, options))}`;
}

function busId(index: number, options: ResolvedOptions): string {
  return `bus-${options.busPrefix.toLowerCase()}${busNumber(index, options)}`;
}

function buildPcsModules(
  stationIndex: number,
  options: ResolvedOptions
): PCSModule[] {
  const sid = stationId(stationIndex, options);
  return Array.from({ length: options.pcsModulesPerStation }, (_, index) => ({
    id: `${sid}-pcs-${index + 1}`,
    manufacturer: options.manufacturer,
    model: options.pcsModuleModel,
    apparentPowerMVA: options.pcsModulePowerMVA,
    nominalAcVoltageV: options.nominalAcVoltageV,
    dcVoltageRangeV: options.dcVoltageRangeV,
  }));
}

function buildBlockTransformer(
  stationIndex: number,
  options: ResolvedOptions,
  stationPowerMVA: number
): BlockTransformer {
  const sid = stationId(stationIndex, options);
  return {
    id: `${sid}-tx`,
    ratedPowerMVA: evidencedNumber(stationPowerMVA, "MVA", options.evidence),
    hvVoltageKv: evidencedNumber(
      options.collectorVoltageKv,
      "kV",
      options.evidence
    ),
    lvVoltageKv: evidencedNumber(options.lvVoltageKv, "kV", options.evidence),
    vectorGroup: options.transformerVectorGroup,
    cooling: options.transformerCooling,
  };
}

function idsAreUnique(ids: string[]): boolean {
  return new Set(ids).size === ids.length;
}

export function generateBlockArchitecture(
  input: BlockArchitectureGeneratorInput
): BlockArchitectureGeneratorResult {
  const options = resolveOptions(input);
  const containers = Math.max(0, Math.floor(input.sizing.containers));
  const stations = Math.max(0, Math.floor(input.sizing.stations));
  const feeders = Math.max(0, Math.floor(input.sizing.feeders));
  const containersPerStation = Math.max(
    1,
    Math.floor(input.sizing.resolved.containersPerStation)
  );
  const stationsPerFeeder = Math.max(
    1,
    Math.floor(input.sizing.resolved.stationsPerFeeder)
  );
  const stationPowerMVA = input.sizing.resolved.stationPowerMVA;
  const feedersPerBus = Math.max(1, Math.floor(options.feedersPerBus));

  if (containers === 0 && stations === 0) {
    return {
      blocks: [],
      conversionStations: [],
      mvFeeders: [],
      mvBuses: [],
      diagnostics: {
        containers,
        stations,
        feeders,
        mvBuses: 0,
        containersPerStation,
        stationsPerFeeder,
        feedersPerBus,
        emptyContainerSlots: 0,
        installedPowerMVA: 0,
      },
    };
  }

  const blocks: BESSBlock[] = [];
  const conversionStations: ConversionStation[] = [];
  let nextContainerIndex = 0;

  for (let stationIndex = 0; stationIndex < stations; stationIndex++) {
    const remainingContainers = Math.max(0, containers - nextContainerIndex);
    const stationContainerCount = Math.min(
      containersPerStation,
      remainingContainers
    );
    const containerIds = Array.from(
      { length: stationContainerCount },
      (_, slot) => containerId(stationIndex, slot + 1, options)
    );
    const block = {
      id: blockId(stationIndex, options),
      name: `BESS block ${options.stationPrefix}${pad(
        stationNumber(stationIndex, options)
      )}`,
      containerIds,
      conversionStationId: stationId(stationIndex, options),
    };
    blocks.push(block);
    conversionStations.push({
      id: block.conversionStationId,
      manufacturer: options.manufacturer,
      model: options.stationModel,
      ratedPowerMVA: evidencedNumber(
        stationPowerMVA,
        "MVA",
        options.evidence
      ),
      pcsModules: buildPcsModules(stationIndex, options),
      blockTransformer: buildBlockTransformer(
        stationIndex,
        options,
        stationPowerMVA
      ),
      associatedContainerIds: containerIds,
      mvFeederId: feederId(
        Math.floor(stationIndex / stationsPerFeeder),
        options
      ),
      evidence:
        options.evidence.length > 0
          ? options.evidence
          : [
              derivedEvidence(
                `${containersPerStation}:1 BESS container to conversion station grouping generated from sizing result`
              ),
            ],
    });
    nextContainerIndex += stationContainerCount;
  }

  const mvFeeders: MVFeeder[] = Array.from({ length: feeders }, (_, index) => {
    const startStationIndex = index * stationsPerFeeder;
    const conversionStationIds = Array.from(
      {
        length: Math.min(stationsPerFeeder, stations - startStationIndex),
      },
      (_, offset) => stationId(startStationIndex + offset, options)
    );
    return {
      id: feederId(index, options),
      nominalVoltageKv: options.collectorVoltageKv,
      ratedPowerMVA: conversionStationIds.length * stationPowerMVA,
      conversionStationIds,
      cableRouteIds: [],
      mvBusId: busId(Math.floor(index / feedersPerBus), options),
      evidence:
        options.evidence.length > 0
          ? options.evidence
          : [
              derivedEvidence(
                `${stationsPerFeeder} conversion stations per MV feeder generated from sizing result`
              ),
            ],
    };
  });

  const mvBusCount = feeders === 0 ? 0 : Math.ceil(feeders / feedersPerBus);
  const mvBuses: MVBus[] = Array.from({ length: mvBusCount }, (_, index) => {
    const startFeederIndex = index * feedersPerBus;
    const feederIds = Array.from(
      {
        length: Math.min(feedersPerBus, feeders - startFeederIndex),
      },
      (_, offset) => feederId(startFeederIndex + offset, options)
    );
    return {
      id: busId(index, options),
      name: `${options.busPrefix}${busNumber(index, options)}`,
      nominalVoltageKv: options.collectorVoltageKv,
      feederIds,
      evidence:
        options.evidence.length > 0
          ? options.evidence
          : [
              derivedEvidence(
                `${feedersPerBus} feeders per MV bus generated from sizing result`
              ),
            ],
    };
  });

  const allIds = [
    ...blocks.map((block) => block.id),
    ...conversionStations.map((station) => station.id),
    ...mvFeeders.map((feeder) => feeder.id),
    ...mvBuses.map((bus) => bus.id),
    ...blocks.flatMap((block) => block.containerIds),
  ];
  if (!idsAreUnique(allIds)) {
    throw new Error("Generated block architecture contains duplicated IDs");
  }

  return {
    blocks,
    conversionStations,
    mvFeeders,
    mvBuses,
    diagnostics: {
      containers,
      stations,
      feeders,
      mvBuses: mvBusCount,
      containersPerStation,
      stationsPerFeeder,
      feedersPerBus,
      emptyContainerSlots: stations * containersPerStation - containers,
      installedPowerMVA: input.sizing.installedPowerMVA,
    },
  };
}
